######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 18 00:51:34 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
OBJECTS_DIR = obj
CONFIG -= qt

# Input
HEADERS += Board.hxx Ren.hxx
SOURCES += Board.cxx main.cxx Ren.cxx
